// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iijgeqltvqwpydvoltou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpamdlcWx0dnF3cHlkdm9sdG91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNzg4NjAsImV4cCI6MjA1Njc1NDg2MH0.LX_i4EajQtlAtcVsIe-d9c329E3yPsUd7-wJJ56InMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);